---
new_page_extension: html
auto_deploy: true
admin_path: "/bh-admin"
webhook_url: 
collections:
- path: _posts
  label: Posts
  create: all
- path: ''
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
